name: Prepare Release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 6'
    - cron: '0 12 * * 3'

jobs:
  deploy:
    name: Prepare Release
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 16

      - name: Checkout CLI for Microsoft 365 Extension
        uses: actions/checkout@v3
        with:
          path: cli-for-microsoft-365-extension
      
      - name: Checkout CLI for Microsoft 365
        uses: actions/checkout@v3
        with:
          repository: pnp/cli-microsoft365
          path: cli-microsoft365

      - name: Checkout PnP Script Samples
        uses: actions/checkout@v3
        with:
          repository: pnp/script-samples
          path: script-samples
      
      - name: Run create script samples script
        run: .\cli-for-microsoft-365-extension\scripts\createScriptSampleDefenition.ps1 -scriptSampleFolderPath ".\script-samples" -cliScriptSampleFolderPath ".\cli-microsoft365\docs\docs\sample-scripts" -workingDirectory ".\cli-for-microsoft-365-extension"
        shell: pwsh
        continue-on-error: false

      - name: Run create snippets script
        run: .\cli-for-microsoft-365-extension\scripts\createSnippetDefenition.ps1 -cliDocsFolderPath ".\cli-microsoft365\docs"
        shell: pwsh
        continue-on-error: false

      - name: Run update package version script
        run: .\cli-for-microsoft-365-extension\scripts\updatePackageVersion.ps1 -currentWorkspace ".\cli-for-microsoft-365-extension"
        shell: pwsh
        continue-on-error: false

      - name: Install dependencies
        run: npm run install:all
        working-directory: cli-for-microsoft-365-extension
      
      - name: Build
        run: npm run vscode:prepublish
        working-directory: cli-for-microsoft-365-extension

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          path: cli-for-microsoft-365-extension
          commit-message: prepare release
          branch: prepare-release
          title: Prepare Release      
          body: Prepare Release
...
